[features]
seeds = false

[programs.localnet]
escrow_contract = "XYP84JFCrTUhWJa3oo7AmiLoXG1fh3XqxpFhAvwPRhy"

[programs.devnet]
escrow_contract = "XYP84JFCrTUhWJa3oo7AmiLoXG1fh3XqxpFhAvwPRhy"

[programs.mainnet]
escrow_contract = "XYP84JFCrTUhWJa3oo7AmiLoXG1fh3XqxpFhAvwPRhy"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/xypher-kp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
