[features]
seeds = false

[programs.localnet]
escrow_contract = "HePXu2ch5nXC82t7sgMCuQVi6QDhjU7q4TR48zhgXvcR"

[programs.devnet]
escrow_contract = "HePXu2ch5nXC82t7sgMCuQVi6QDhjU7q4TR48zhgXvcR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/swarnab/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
